config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  # Static Pages
  get 'static_pages/home'
  get 'static_pages/keyboard'
  get 'static_pages/help'
  get 'static_pages/clock'
  get 'static_pages/site'
  get 'static_pages/rankings'
  
  # Simple User for JSon test
  resources :users do
    resources :stats
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stat.rb
class Stat < ApplicationRecord
    
    belongs_to :user
    

    def add_points
        points = self.score + rand(50)
        update_attribute(:score, points)
    end
    
    def subtract_points
        points = self.score - rand(50)
        update_attribute(:score, points)
    end
    
end

app/models/user.rb
class User < ApplicationRecord
    has_one :stat, dependent: :destroy
    
    validates :name, presence: true
    validates :email, presence: true
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
      render html: "hello y'all"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end
  
  def keyboard
  end
  
  def gate
  end
  
  def clock
  end
  
  def site
  end
  
  def rankings
    @users = User.first(3)
    
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  private
  
  def update_ranking
    @users = User.last(3)
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
    def create
        #@user = User.find(params[:user_id])
        @stat = @user.stats.create(stat_params)
        @stat[:score] = rand(50..100)
        redirect_to user_path(@user)
    end
    
    private
        def stat_params
            params.require(:stat).permit(:score)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def new
    end
    
    def edit
        @user = User.find(params[:id])
    end
    
    def create
        @user = User.new(user_params)
        @stat = @user.create_stat(score: 25)
       
        if @user.save
            redirect_to @user
        else
            render 'new'
        end
    end
    
    def updated
        @user = User.find(params[:id])
        
        if @user.update(user_params)
            redirect_to @user
        else
            render 'edit'
        end
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        
        redirect_to users_path
    end
    
    private
        def user_params
            params.require(:user).permit(:name, :email)
        end
            
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deadco</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">D.E-ad.co</a>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shared/_scoreboard.html.erb
<div class="score-container">
    <div class="row align-items-center">
        <div class="col">
            <h1>Score</h1>
            <div class="final-score">
                <%= @user.stat.score %>    
            </div>
            <div class="result">Awesome!</div>        
        </div>
    </div>
</div>

app/views/static_pages/clock.html.erb
<div class="clock">
  <div class="clock-face">
    <div class="hand hour-hand"></div>
    <div class="hand min-hand"></div>
    <div class="hand second-hand"></div>
  </div>
</div>

<script>
    const secondHand = document.querySelector('.second-hand');
    const minsHand = document.querySelector('.min-hand');
    const hourHand = document.querySelector('.hour-hand');

    function setDate() {
        const now = new Date();
    
        const seconds = now.getSeconds();
        const secondsDegrees = ((seconds / 60) * 360) + 90;
        secondHand.style.transform = `rotate(${secondsDegrees}deg)`;
    
        const mins = now.getMinutes();
        const minsDegrees = ((mins / 60) * 360) + ((seconds/60)*6) + 90;
        minsHand.style.transform = `rotate(${minsDegrees}deg)`;
        
        const hour = now.getHours();
        const hourDegrees = ((hour / 12) * 360) + ((mins/60)*30) + 90;
        hourHand.style.transform = `rotate(${hourDegrees}deg)`;
    }

    setInterval(setDate, 1000);
    setDate();
</script>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<%= render partial:"shared/navbar" %>
<div class="container-fluid hero">  
</div>

<div class="inner cover">
    <h1 class="cover-heading">Cover your page.</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
    </p>
</div> 
<p>Find me in app/views/static_pages/home.html.erb</p>
<p>
    <h1>HELLO</h1>
    <%= link_to "New User", new_user_path %> |
    <%= link_to "Users", controller: "users" %>
</p>

<h1 class="title">jQuery Test</h1>
<div id="main-div">
    </br>
    <h1>This is an h1</h1>
    <h1>Another H1</h1>
    <h2>h2 class</h2>
    <h3>h3 One</h3>
    <h3>h3 Two</h3>
    <h3>h3 Three</h3>
    <input type="button" id="button1" value="Randomize Headings"/>
    <input type="button" id="button2" value="Revert Headings"/>
</div>

app/views/static_pages/keyboard.html.erb
<body>


  <div class="keys">
    <div data-key="65" class="key">
      <kbd>A</kbd>
      <span class="sound">clap</span>
    </div>
    <div data-key="83" class="key">
      <kbd>S</kbd>
      <span class="sound">hihat</span>
    </div>
    <div data-key="68" class="key">
      <kbd>D</kbd>
      <span class="sound">kick</span>
    </div>
    <div data-key="70" class="key">
      <kbd>F</kbd>
      <span class="sound">openhat</span>
    </div>
    <div data-key="71" class="key">
      <kbd>G</kbd>
      <span class="sound">boom</span>
    </div>
    <div data-key="72" class="key">
      <kbd>H</kbd>
      <span class="sound">ride</span>
    </div>
    <div data-key="74" class="key">
      <kbd>J</kbd>
      <span class="sound">snare</span>
    </div>
    <div data-key="75" class="key">
      <kbd>K</kbd>
      <span class="sound">tom</span>
    </div>
    <div data-key="76" class="key">
      <kbd>L</kbd>
      <span class="sound">tink</span>
    </div>
  </div>

    <audio data-key="65" src="<%= audio_path("/sounds/clap.wav")%>"></audio>
    <audio data-key="83" src="<%= audio_path("/sounds/hihat.wav")%>"></audio>
    <audio data-key="68" src="<%= audio_path("/sounds/kick.wav")%>"></audio>
    <audio data-key="70" src="<%= audio_path("/sounds/openhat.wav")%>"></audio>
    <audio data-key="71" src="<%= audio_path("/sounds/boom.wav") %>"></audio>
    <audio data-key="72" src="<%= audio_path("/sounds/ride.wav") %>"></audio>
    <audio data-key="74" src="<%= audio_path("/sounds/snare.wav") %>"></audio>
    <audio data-key="75" src="<%= audio_path("/sounds/tom.wav") %>"></audio>
    <audio data-key="76" src="<%= audio_path("/sounds/tink.wav") %>"></audio>

  <style>
    html {
      font-size: 10px;
      background: url(http://i.imgur.com/b9r5sEL.jpg) bottom center;
      background-size: cover;
    }
    body,html {
      margin: 0;
      padding: 0;
      font-family: sans-serif;
    }
    
    .keys {
      display: flex;
      flex: 1;
      min-height: 100vh;
      align-items: center;
      justify-content: center;
    }
    
    .key {
      border: .4rem solid black;
      border-radius: .5rem;
      margin: 1rem;
      font-size: 1.5rem;
      padding: 1rem .5rem;
      transition: all .07s ease;
      width: 10rem;
      text-align: center;
      color: white;
      background: rgba(0,0,0,0.4);
      text-shadow: 0 0 .5rem black;
    }
    
    .playing {
      transform: scale(1.1);
      border-color: #ffc600;
      box-shadow: 0 0 1rem #ffc600;
    }
    
    kbd {
      display: block;
      font-size: 4rem;
    }
    
    .sound {
      font-size: 1.2rem;
      text-transform: uppercase;
      letter-spacing: .1rem;
      color: #ffc600;
    }
  </style>  
  <script>
    function playSound(e) {
        const audio = document.querySelector(`audio[data-key="${e.keyCode}"]`);
        const key = document.querySelector(`div[data-key="${e.keyCode}"]`);
        if (!audio) return; //stop function running all together
        audio.currentTime = 0; //rewind to start
        audio.play();
        key.classList.add('playing');
    }
    
    function removeTransition(e) {
        if (e.propertyName !== 'transform') return;
        console.log(e.propertyName);
        this.classList.remove('playing');
    }
      
     const keys = Array.from(document.querySelectorAll('.key'));
     keys.forEach(key => key.addEventListener('transitionend', removeTransition));
     window.addEventListener('keydown', playSound);  
  </script>

</body>

app/views/static_pages/rankings.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1 class="text-center"><span class="badge badge-default">Good</span></h1>
            <table class="table table-inverse">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Score</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td><%= @users[1].name %></td>
                  <td><%= @users[1].email %></td>
                  <td><%= @users[1].stat.score %></td>
                </tr>
                 <tr>
                  <th scope="row">2</th>
                  <td>Mark</td>
                  <td>Otto</td>
                  <td>@mdo</td>
                </tr>
                 <tr>
                  <th scope="row">3</th>
                  <td>Mark</td>
                  <td>Otto</td>
                  <td>@mdo</td>
                </tr>
              </tbody>
            </table>
        </div>
    </div>
    <h2><strong>UPDATE</strong></h2>
</div>

app/views/stats/_stat.html.erb
<div class="container">

    <div class="stop-game game-full-flex">
      <div class="score">

        <div class="score-container">

            <h1>Score</h1>

            <div class="final-score">
                <%= @user.stats.score %>
            </div>
            <div class="result">Awesome!</div>
        </div>
        
      </div>

    </div>

    <div class="small-glows"></div>

    <div class="glow"><div class="sun"></div></div>

    <div class="waves">
        <div class="top_wave"></div>
        <div class="wave1"></div>
        <div class="wave2"></div>
        <div class="wave3"></div>
        <div class="wave4"></div>
    </div>

    <div class="mounts">
        <div class="mount1"></div>
        <div class="mount2"></div>
    </div>

    <div class="clouds"></div>


    <div class="noise"></div>

</div>

<style>
    body {
    background-color: #28DAD4;
    margin: 0;
    padding: 0;
    overflow: hidden;
    font-family: 'Roboto', sans-serif;
}

body * {
    -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Chrome/Safari/Opera */
     -khtml-user-select: none; /* Konqueror */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version, currently
                                  not supported by any browser */
}

a {
    cursor: url(https://greghub.github.io/coloron/public/svg/cursor.svg), pointer;
    &:focus, &:active {
    cursor: url(https://greghub.github.io/coloron/public/svg/cursor-tap.svg), pointer;
    }
}
.container {
    position: fixed;
    left: 0;
    top: 0;
    height: 100%;
    width: 100%;
}
.waves, .mounts {
    position: absolute;
    width: 100%;
    left: 0;
    bottom: 0;
}
.waves div, .mounts div {
    position: absolute;
    width: 100%;
}
.clouds {
    position: absolute;
    width: 100%;
    left: 0;
    top: 77px;
    height: 151px;
    background: url(https://greghub.github.io/coloron/public/svg/clouds.svg) repeat-x;
    background-position-x: 170px; 
}
.top_wave {
    background: url(https://greghub.github.io/coloron/public/svg/top_wave.png) repeat-x 0 -1px;
    height: 35px;
    bottom: -1px;
    z-index: 10001;
}
.wave1 {
    background: url(https://greghub.github.io/coloron/public/svg/wave1.svg) repeat-x;
    height: 150px;
    bottom: 0;
    z-index: 23;
}
.wave2 {
    background: url(https://greghub.github.io/coloron/public/svg/wave2.svg) repeat-x;
    height: 180px;
    bottom: 30px;
    z-index: 22;
}
.wave3 {
    background: url(https://greghub.github.io/coloron/public/svg/wave3.svg) repeat-x;
    height: 180px;
    bottom: 90px;
    z-index: 21;
}
.wave4 {
    background: url(https://greghub.github.io/coloron/public/svg/wave4.svg) repeat-x;
    height: 180px;
    bottom: 120px;
    z-index: 20;
}
.mount1 {
    background: url(https://greghub.github.io/coloron/public/svg/mount1.svg) repeat-x;
    height: 150px;
    bottom: 280px;
    z-index: 11;
}
.mount2 {
    background: url(https://greghub.github.io/coloron/public/svg/mount2.svg) repeat-x;
    height: 150px;
    bottom: 290px;
    z-index: 10;
}
.noise {
    position: fixed;
    width: 100%;
    height: 100%;
    left: 0;
    top: 0;
    z-index: 1010;
    background: url(https://greghub.github.io/coloron/public/svg/noise.png);
}
.glow {
    position: absolute;
    left: -350px;
    top: -350px;
    width: 800px;
    height: 800px;
    background-color: rgba(81, 237, 200, 0.34);
    border-radius: 50%;
    box-shadow: 0 0 100px 100px rgba(81, 237, 200, 0.34);
    z-index: 1010;
}
.sun {
    position: relative;
    left: 50%;
    top: 50%;
    width: 1px;
    height: 1px;
    background-color: rgba(255, 227, 69, 1);
    border-radius: 50%;
    box-shadow: 0 0 32px 32px rgba(255, 227, 69, 1), 
                0 0 150px 150px rgba(103, 244, 210, 0.4);
}
.small-glow {
    z-index: 99;
    width: 12px;
    height: 12px;
    border-radius: 50%;
    position: absolute;
    background-color: rgba(255, 255, 255, 0.34);
    box-shadow: 0 0 1px 1px rgba(255, 255, 255, 0.34);
}
.small-glow.yellow {
    background-color: rgba(255, 227, 69, 0.34);
    box-shadow: 0 0 4px 4px rgba(255, 227, 69, 0.34);
}

.game-full-flex {
    position: fixed;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    align-items: center;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    z-index: 99999;
}
.stop-game {
    justify-content: center;
    .score {
        display: inherit;
    }
    .score-container {
        background-color: #4C4660;
        width: 433px;
        height: 386px;
        border-radius: 38px;
        text-align: center;
        h1 {
            color: #fff;
            text-transform: uppercase;
            letter-spacing: -0.1em;
            margin-top: 20px;
            margin-bottom: 4px;
            font-size: 64px;
        }
        .final-score {
            color: #FFE345;
            font-weight: 900;
            font-size: 130px;
            letter-spacing: -6px;
            line-height: 110px;
        }
        .result {
            color: #FF4571;
            text-transform: uppercase;
            font-weight: 700;
            font-size: 30px;
        }
        h4 {
            color: #fff;
            margin-top: 12px;
        }
        
        .main-menu {
            background-color: #44BFA3;
            border: 2px solid #fff;
            color: #fff;
            text-decoration: none;
            text-transform: uppercase;
            font-weight: 900;
            letter-spacing: -1px;
            font-size: 26px;
            padding: 6px 24px;
            border-radius: 22px;
            margin: 6px 4px;
            display: inline-block;
            &:hover {
                background-color: lighten(#44BFA3, 5%);
            }
        }
    }
}

@media screen and (max-height: 480px) {
    .stop-game .score {
      background-color: #4C4660;
      width: 433px;
      height: 386px;
      border-radius: 38px;
      text-align: center;
      transform: scale(0.6);
    }
    .glow {    
        width: 240px;
        height: 240px;
        left: -90px;
        top: -90px;
    }
    .sun {
        box-shadow: 0 0 20px 20px rgba(255, 227, 69, 1), 
                    0 0 150px 150px rgba(103, 244, 210, 0.4);
    }
    .small-glow {
        transform: scale(0.5);
    }
    .waves div {
        background-size: auto 100%
    }
    .wave1, .wave2, .wave3, .wave4 {
        height: 80px;
    }
    .top_wave {
        height: 20px;
    }
    .wave1 {
        bottom: -20px;
    }
    .wave2 {
        bottom: 10px;
    }
    .wave3 {
        bottom: 40px;
    }
    .wave4 {
        bottom: 60px;
    }
    .mount1 {
        background-size: auto 80%;
        height: 80px;
        bottom: 120px;
    }
    .mount2 {
        background-size: auto 80%;
        height: 120px;
        bottom: 130px;
    }
    .clouds {
        top: 25px;
        height: 60px;
        background-size: auto 100%;
    }
}
@media screen and (max-height: 320px) {
    .rotate {
        position: fixed;
        z-index: 99999;
        background-color: #28DAD4;
        width: 100%;
        height: 100%;
        left: 0;
        top: 0;
        display: block;
        text-align: center;
        text-transform: uppercase;
        color: #fff;
    }
    .rotate:before {
        display: block;
        content: " ";
        height: 40%;
    }
}
</style>

<script>
    $(document).ready(function(){
          var resultTimeline = new TimelineMax();
              resultTimeline
                  .fromTo('.stop-game .score-container', 0.7, { opacity: 0, scale: 0.3 }, { opacity: 1, scale: 1, ease: Elastic.easeOut.config(1.25, 0.5)})
                  .fromTo('.stop-game .final-score', 2, { scale: 0.5 }, { scale: 1, ease: Elastic.easeOut.config(2, 0.5)}, 0)
                  .fromTo('.stop-game .result', 1, { scale: 0.5 }, { scale: 1, ease: Elastic.easeOut.config(1.5, 0.5)}, 0.3;
</script>

app/views/users/_form.html.erb
<h1> New User </h1>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-sm-6">
            <%= form_for @user do |f| %>
              
              <% if @user.errors.any? %>
                <div id="error_explanation">
                  <h2>
                      <%= pluralize(@user.errors.count, "error") %> kept user from being saved:
                  </h2>
                  <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              
              <p>
                <%= f.label :name %><br>
                <%= f.text_field :name %>
              </p>
             
              <p>
                <%= f.label :email %><br>
                <%= f.text_area :email %>
              </p>
             
              <p>
                <%= f.submit %>
              </p>
            <% end %>
        </div>
        <%= link_to 'Back', users_path %>
    </div>
</div> <!-- /container -->

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>
<%= render partial:"shared/scoreboard", object: @user %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
 
<table>
  <tr>
    <th>Name:  </th>
    <th>E-mail:  </th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= render partial:"shared/scoreboard", object: @user %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
                      method: :delete,
                      data: { confirm: "Are you sure you 
                        want to make a bad decision?" } %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1> New User </h1>
<div class="row justify-content-md-center">
    <div class="col-sm-6">
        <%= form_for :user, url: users_path do |f| %>
          
          <p>
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </p>
         
          <p>
            <%= f.label :email %><br>
            <%= f.text_area :email %>
          </p>
         
          <p>
            <%= f.submit %>
          </p>
        <% end %>
    </div>
</div>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-sm-6">
            <p>
              <strong>Name:</strong>
                  <%= @user.name %>
            </p>
             
            <p>
              <strong>Email:</strong>
              <%= @user.email %>
            </p>
            
            <div>
                <%= render partial:"shared/scoreboard", object: @user %>
            </div>
                
            
            <%= link_to 'Edit', edit_user_path(@user) %> |
            <%= link_to 'Back', users_path %>
        </div>
    </div>
</div>